language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.4"

install:
  - "pip install --use-mirrors -e ."
  - "pip install --use-mirrors nose coverage"

script: nosetests --with-coverage --cover-inclusive --cover-package=sshim
